### ISSUE TITLE
1 Sprint - Jedilson

### ISSUE THREAD

**Issue by profissionaljpj** [FernandaAmanda/ProjetoUnibratec#11]
7 - JEDILSON - Elaboração dos layouts, conectividade dos menus com o banco de dados, criação da tela gerencial e demais telas, sem a necessidade de haver suas funcionalidades (Elaborar todo o fluxo de telas).

**Comment by Jedilson** [comment]
Jair, não entendi o 'Conectividade dos menus com o banco de dados' me explica melhor isso aí.

**Comment by brunopereiraXD** [comment]
Bom Dia!
Conforme conversado entrega para o dia 14-10-2014.
Sobre sua dúvida vou procurar com Jair e Carlos do gp.
Abraços

**Comment by brunopereiraXD** [comment]
Boa Tarde.

Foi enviado para github.
Abraços
