### ISSUE TITLE
Fernanda.

### ISSUE THREAD

**Issue by NandoLeimig** [FernandaAmanda/ProjetoUnibratec#12]
Nanda, onde você pegou o layout to site? é bem interessante, me manda o link para eu ver quais ferramentas tem a mais disponíveis lá, pode ser que precisemos de algo.

**Comment by NandoLeimig** [comment]
é WebMedia?

**Comment by FernandaAmanda** [comment]
Nando,eu preciso que vcs coloquem no site a parteem  PHP pra mostrar as senhas,bem simples.

**Comment by FernandaAmanda** [comment]
Tem como vc fazer isso com o grupo? São necessárias poucas modificações,porque o designer não vejo muito o que mudar.

**Comment by NandoLeimig** [comment]
faz ai se é simples :+1: kkk! Verei.

**Comment by brunopereiraXD** [comment]
Boa Tarde!

O layout enviado por Fernanda para github.
Falta a pessoa que ficou responsável pelo layout terminar.

Abraços
