### ISSUE TITLE
Web Project

### ISSUE THREAD

**Issue by NandoLeimig** [FernandaAmanda/ProjetoUnibratec#13]
Apenas algumas sugestões para o pessoal ai de Web:
usuario = usuário 
podera = poderá
preoculpar = preocupar

"Por meio do nosso site nossos usuarios possuem acesso em qualquer lugar e a qualquer momento as atualizações de senhas de Guichê,o o cliente podera ficar tranquilo sem se preoculpar de perder sua vez na fila"

A imagem da logo vai ficar com o quadrado azul ao redor?

Casos de uso do site:
UC005.2. O sistema busca o registro da última senha gerada e da última senha chamada para mostrar no site incluindo o guichê e um histórico com as últimas três senhas chamadas com os guichês correspondentes. 
UC005.3. O sistema mostra no site a data da última atualização do site.

Pós-condição: A última senha chamada com o guichê, a última senha gerada e o histórico das últimas três senhas. A data de atualização ter sido atualizada no site.

Não consegui identificar esses casos de uso na index.

Segue sugestão.

**Comment by brunopereiraXD** [comment]
boa dia.

equipe que esta no planejamento do site olhada os itens citados acima.

agradeço atenção de todos.
