### ISSUE TITLE
Erro no Banco de dados

### ISSUE THREAD

**Issue by Jedilson** [FernandaAmanda/ProjetoUnibratec#14]
Estou tendo um erro ao conectar com o banco, alguém pode me ajudar?
Mesmo especificando um usuário e senha eu tenho o mesmo erro, seguem os detalhes:   

![sem titulo](https://cloud.githubusercontent.com/assets/8379058/4606202/f560ebb8-5213-11e4-98bb-318ea994760a.jpg)

String de Conexão:
private static string ConnectionString = "Server=JEDILSON-PC;Database=PocketQueue;";
Erro:
"An unhandled exception of type 'System.InvalidOperationException' occurred in EntityFramework.dll

Additional information: This operation requires a connection to the 'master' database. Unable to create a connection to the 'master' database because the original database connection has been opened and credentials have been removed from the connection string. Supply an unopened connection."

**Comment by Jedilson** [comment]
Consegui :DD

**Comment by NandoLeimig** [comment]
Massa!

**Comment by brunopereiraXD** [comment]
Que bom.
