### ISSUE TITLE
Não consigo retornar dados

### ISSUE THREAD

**Issue by Jedilson** [FernandaAmanda/ProjetoUnibratec#16]
Não estou conseguindo retornar os usuarios cadastrados no sistema usando o seguinte código:

 //Só precisa disso!
            IRepositorioUsuario usuario = new RepositorioUsuario();
            List<Usuario> usuariosCadastradosNoSistema = usuario.ListarUsuarios();

Estou com problemas  na classe 'RepositorioUsuario' no método 'Listar usuário' no Projeto 'DatabasePocketQueue', o programa chega nessa linha e não continua, é preciso parar o debug.Sequer o Visual Studio mostra algum erro.

![sem titulo](https://cloud.githubusercontent.com/assets/8379058/4759678/6be57596-5ae9-11e4-93c3-295f04de1696.png)

**Comment by NandoLeimig** [comment]
A mesma coisa comigo,

**Comment by brunopereiraXD** [comment]
Boa Tarde!
Falar com Carlos pode ajudar nesta dúvida.
