### ISSUE TITLE
Codigo cheio de erros

### ISSUE THREAD

**Issue by Jedilson** [FernandaAmanda/ProjetoUnibratec#17]
O último commit está cheio de erros por todo o código a ponto de o Visual Studio não conseguir abrir o projeto, favor ver o que houve.

**Comment by NandoLeimig** [comment]
Também não consegui abrir, o código está cheio de conflitos. Favor rever Victor.

**Comment by brunopereiraXD** [comment]
Boa Tarde!
Victor conseguiu rever seu commit?
Leva seu notebook para aula, ajudamos você.
