### ISSUE TITLE
Duvidas

### ISSUE THREAD

**Issue by FernandaAmanda** [FernandaAmanda/ProjetoUnibratec#18]
As pessoas que não estão conseguindo fazer sua parte no projeto,por favor falar comigo ou bruno para manter agente informado da situação e como podemos ajudar,procurar ajuda com Carlos.

**Comment by henriqueleite** [comment]
Esqueceram de mim #2

Tá faltando a minha parte para fazer no projeto depois que vocês atualizaram a tarefas. Fui sexta com  
Luiz fazer a parte dele, falta pouco para terminar a parte dele.

**Comment by FernandaAmanda** [comment]
Beleza,vou falar com o grupo para resolver o que você pode fazer e aviso.

**Comment by henriqueleite** [comment]
Ok, se faltar tarefas eu posso continuar ajudando os outros como ajudei Luiz. Pq Eudes e victor tbm estão com algumas dificuldades.

**Comment by brunopereiraXD** [comment]
Bom Noite!

Henrique Leite irá ajudar Victor Luiz.
Informado ao GP.
Equipe Fernanda e Bruno

**Comment by FernandaAmanda** [comment]
Quem tiver mais dificuldades,ou caso não esteja conseguindo fazer o que foi pedido por favor avisar logo

**Comment by HenriqueLh** [comment]
To com duvidas! ;-)
Em 16/11/2014 21:04, "FernandaAmanda" notifications@github.com escreveu:

**Comment by brunopereiraXD** [comment]
Bom Dia
Henrique qual séria sua dúvida?
Leve hoje para aula.
Abraços

**Comment by HenriqueLh** [comment]
Provavelmente estarei chegando mais cedo para buscar a solução com jedilson.
Em 19/11/2014 08:58, "Bruno Pereira" notifications@github.com escreveu:

**Comment by FernandaAmanda** [comment]
Problema resolvido?

**Comment by HenriqueLh** [comment]
Ainda não... Faremos o maximo pra estarmos prontos durante esse resto de
semana.
Em 20/11/2014 22:58, "FernandaAmanda" notifications@github.com escreveu:

**Comment by brunopereiraXD** [comment]
Bom Dia Companheiros.

Fique atentos o prazo do projeto para mandar no github até sábado dia 29 às 24:00 ou 12:00 noite, conforme informado pelo GP na aula de ontem.
Dúvidas é só perguntar para equipe puder ajudar.

Equipe
Fernanda e Bruno
