### ISSUE TITLE
Revisão de Código (02/10/2014 - 21:04)

### ISSUE THREAD

**Issue by WickedPeanuts** [FernandaAmanda/ProjetoUnibratec#2]
Revisão do commit b1051bca61.

Primeiro gostaria de dizer que o projeto que foi feito commit não está compilando, além de existir uma form que não abre, pois seu código foi modificado indevidamente. Além de existirem elementos com referências perdidas e variáveis com nomes genéricos que irão confundir os demais programadores.

LoginScreen.cs

Form (Visual)
1 - O botão de cadastrar não pode estar na tela principal.
2 - Deve ser fisicamente um botão, e não um Label com hiperlink.
3 - Apenas usuários com privilégios podem acessar esta funcionalidade.
4 - O tamanho da janela não está proporcional ao tamanho dos links.

Código
1 - Linha 48: Cadastre_LinkClicked - Esta função não deveria existir.
1.1 - Linha 50: As telas devem ser geradas em uma Factory de telas.
1.2 - Linha 51: A LoginScreen é instanciada e então fechada, isto não faz sentido uma vez que você não quer uma nova login screen.
1.3 - Linha 52: A tela recém instanciada é fechada.

TelaCadastroUsuario.cs

Form (Visual)
1 - Campos flutuantes em todas as posições, eles não estão organizados, esteticamente deplorável.
2 - Os botões de submeter a form (OK! e Cancelar!!) estão com labels indevidos. O correto há de ser Cancelar e Cadastrar.
3 - IDTipoUsuario é uma chave estrangeira, ele deveria se remeter à um tipo de usuário, e não um ID para cadastro.
4 - A senha é um campo sigiloso, não pode ser mostrado para os usuários.
5 - Há de haver outro campo para validar se a senha inserida é realmente a esperada.
6 - Cada label deve possuir um ":" após suas strings.
7 - A label TipoResidencia está sem espaçamento, além de não haver acento circunflexo no segundo E de residência.
8 - Os campos relativos à endereço devem estar próximos.

Código
1 - Múltiplas ocorrências de funcionalidades para labels não implementadas, lixo de código, linhas 20 à 43.
2 - As referências para as mesmas também deve ser deletadas na classe de instanciação da tela.
3 - Linha 52: Login é instanciado novamente e permanece sem utilidade.
4 - O botão não possui funcionalidade alguma.

TelaGerente.cs

Não funciona.

TelaConsulta.cs

Form(Visual)
1 - A tela não demonstra utilidade alguma para o usuário, não está claro qual o seu papel.
2 - Não há possibilidade de acessar a tela.

Código
1 - Telas instanciadas fora de um factory.
2 - Esta tela só fecha após a tela do gerente fechar, foi esse o propósito da mesma?

**Comment by fchicout** [comment]
Sugiro fortemente a criação de um issue no github para cada um desses
problemas.
Esses são bugs de sistema, e precisam ser registrados para serem corrigidos.

Grupo, foco na resolução dos problemas relatados!

Em 2 de outubro de 2014 21:35, WickedPeanuts notifications@github.com
escreveu:

**Comment by brunopereiraXD** [comment]
Bom Dia Carlos.

Verifique o pdf do caso de uso PocketQueQue não consta o cadastro de usuário, tomei a iniciativa realizei a tela de cadastro de usuário. Fiz um link de "cadastre -se" puxando a tela de cadastro.  Preciso de orientação da onde a tela vai ser inicializado..e detalhes da tela de cadastro.

**Comment by brunopereiraXD** [comment]
Boa Noite!
A tela de cadastro de usuario foi feita com base que consta no DAO/Entidades/Usuario e seus respectivos atributos (nome, sobreNome, cpf, rg, tipoResidencia, endereco, complemento, numero, login, senha, idTipoUsuario).
Feito algumas as correções da tela de cadastro de usuário.
Form:
1 - Ver as posições estão  organizadas.
2 - Alterado os nomes de submeter(OK! e Cancelar!!)  para Cancelar e Cadastrar.
os itens 3 à 5 com dúvidas.
6 - Colocado em cada label  " : ".
7 - Correção do nome e com espaço.
8 - Referentes a endereços.

Verifique se esta certo o que foi pedido.
Feito apenas a Tela de cadastro de usuário.

**Comment by FernandaAmanda** [comment]
Os meninos da parte de desenvolvimento estao iniciando comigo o site do mosso projeto,vamos dividir o que cada um ira fazer e deixar todos informados por meio do github.
