### ISSUE TITLE
1 Sprint - Leonardo

### ISSUE THREAD

**Issue by profissionaljpj** [FernandaAmanda/ProjetoUnibratec#6]
2 - LEONARDO - Comunicação com o banco de dados SQL Server {UC004} (2008/2012/2013 [é tudo o mesmo código])

**Comment by brunopereiraXD** [comment]
Bom Dia!

Conversado ontem entrega para o dia 14-10-2014.

Abraços

**Comment by brunopereiraXD** [comment]
Boa Tarde!

Leonardo conseguiu fazer alguma coisa da sua parte Comunicação com o banco de dados SQL Server?
Aguardando resposta.

Abraços
