### ISSUE TITLE
1 Sprint - Luis Henrique

### ISSUE THREAD

**Issue by profissionaljpj** [FernandaAmanda/ProjetoUnibratec#8]
4 - LUIS HENRIQUE - Elaborar a tela do recepcionista (Gerar senhas), caso de uso: Gerar senha. E conectá-la ao menu principal e ao banco de dados.

**Comment by brunopereiraXD** [comment]
Boa Noite!

A tela de recepcionista será entregue no dia 14-10-14.

**Comment by brunopereiraXD** [comment]
Boa Tarde!

Luis Henrique conseguiu fazer a tela do recepcionista (Gerar senhas), caso de uso: Gerar senha. E conectá-la ao menu principal e ao banco de dados?
No aguardo da resposta.

Abraços
