### ISSUE TITLE
1 Sprint - Nando

### ISSUE THREAD

**Issue by profissionaljpj** [FernandaAmanda/ProjetoUnibratec#9]
5 - NANDO - Finalizar a tela de cadastro, corrigir os bugs citados no issues do github. Além de conectá-la ao menu do gerente (se não houver, criá-lo) e em seguida conectá-lo ao banco de dados.

**Comment by NandoLeimig** [comment]
Tela de Cadastro ok!
bugs citados já foram corrigidos.
Tela de Cadastro já está conectada a tela do gerente.
""
            this.Hide();
            TelaCadastroUsuario TelaCadastroUsuario = new TelaCadastroUsuario();
            TelaCadastroUsuario.ShowDialog();
            this.Close();

"" verificar apenas se está de acordo com o solicitado.

Conectar ao Bando de Dados já está combinado com Carlos para resolver.
